apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat04
  namespace: dev
spec:
  template:
    metadata:
      labels:
        app: tomcat04
    spec:
      containers:
      - image: swr.ap-southeast-2.myhuaweicloud.com/paas-poc/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: tomcat04
        env:
        - name: branch
          value: <BRANCH_NAME>
